### ISSUE TITLE
C file with errors

### ISSUE THREAD

**Issue by thiagottjv** [hoelzro/linux-fake-battery-module#1]
Hi,

First of all... I was looking for this on the last days and I'm so glad I found it.

Second... when I make the file it shows a lot of errors...

Do you have a more recent file?
Here is the errors:
![virtualbox_raspberry pi_22_01_2017_00_51_23](https://cloud.githubusercontent.com/assets/4126003/22179819/f5212e24-e03c-11e6-92e5-2e4c81cad56a.png)

**Comment by hoelzro** [comment]
Hi @thiagottjv,

It looks like you're building against Linux 3.16 - I believe (from my package manager logs) that I build this against Linux 4.2.5.  I'm guessing that the kernel battery API has changed since 3.16 - namely that `power_supply_desc` doesn't exist in the old kernels.  From a cursory glance, it looks like a pretty simple fix - just change the `power_supply_desc` and `power_supply_config` structs to `power_supply` ones, and change the call to `power_supply_register` accordingly.
